#![allow(unused_imports, dead_code)]

use anyhow::{Result, Context};
use base64::{engine::general_purpose::STANDARD as B64, Engine};
use crate::core::crypto::{CryptoProvider, OlmSessionHandle, MegolmOutbound};
use crate::utils::logging::VerbosityLevel;
use crate::vlog;
use super::*;

#[allow(dead_code)]
impl MatrixRoom {
    /// Encrypts a Megolm session key via the Olm channel (multi-sender mode).
    pub(crate) fn encrypt_megolm_key_via_olm_multi_sender(&mut self, sender_id: &str, session_key: &[u8], receiver_id: &str) -> Result<Vec<u8>> {
        let start_time = std::time::Instant::now();
        
        vlog!(VerbosityLevel::Verbose, "      [ENCRYPT_CALL] {} -> {}", sender_id, receiver_id);
        
        let sender = self.members.get_mut(sender_id)
            .context("Sender not found")?;
        
        let olm_session_pair = sender.olm_sessions.get_mut(receiver_id)
            .context("Olm session not found")?;
        
        // Apply any pending KEM ciphertext generated by the inbound side during a forced ratchet.
        if let Some(pending_kem) = olm_session_pair.pending_kem_for_outbound.take() {
            if let Some(ref mut olm_session) = olm_session_pair.outbound {
                olm_session.hybrid_session.set_pending_kem_ciphertext(pending_kem.clone());
                vlog!(VerbosityLevel::Debug, "       [ENCRYPT] {} -> {}: using shared KEM from inbound ({} bytes)", 
                     sender_id, receiver_id, pending_kem.len());
            }
        }
        
        let olm_session = olm_session_pair.get_outbound_mut()
            .context("Olm outbound session not found")?;

        let ratchet_before = olm_session.get_ratchet_advances();
        let asymmetric_before = olm_session.get_asymmetric_advances();

        let encrypted_key = sender.crypto.olm_encrypt(olm_session, session_key);

        let ratchet_after = olm_session.get_ratchet_advances();
        let asymmetric_after = olm_session.get_asymmetric_advances();
        
        if ratchet_after > ratchet_before {
            self.num_ratchet_advances += (ratchet_after - ratchet_before) as usize;
        }
        if asymmetric_after > asymmetric_before {
            self.num_asymmetric_advances += (asymmetric_after - asymmetric_before) as usize;
        }
        
        vlog!(VerbosityLevel::Debug, "       [ENCRYPT] room={}, {} -> {}, size={} bytes, setup={}, mode={:?}", 
                 self.room_id, sender_id, receiver_id, encrypted_key.len(), self.in_setup_phase, self.crypto_mode);
        
        // Track bandwidth by phase: type 0/1 = classical Olm, type 2 = hybrid PQC Olm.
        
        // Extrair breakdown REAL dos componentes da mensagem PQC
        let (classical_bytes, pqc_bytes) = Self::extract_message_breakdown(&encrypted_key, &self.crypto_mode);
        
        let elapsed = start_time.elapsed().as_secs_f64() * 1000.0;

        if self.in_setup_phase {
            // Initial distribution phase: counts toward Megolm session key distribution.
            self.bandwidth_session_distribution += encrypted_key.len();
            self.time_initial_distribution_ms += elapsed;
            
            self.bandwidth_initial_distribution += encrypted_key.len();
            self.bandwidth_initial_distribution_classical += classical_bytes;
            self.bandwidth_initial_distribution_pqc += pqc_bytes;
            self.bandwidth_control_plane += encrypted_key.len();
            
            // Parse wire format to isolate primitive contributions (Megolm key, ratchet key, KEM CT).
            let megolm_key_size = 308;
            self.bandwidth_initial_distribution_primitives_megolm_key += megolm_key_size;
            
            // Parse per-primitive contributions from the wire message.
            if let Ok(json_val) = serde_json::from_slice::<serde_json::Value>(&encrypted_key) {
                let msg_type_val = json_val.get("type").and_then(|t| t.as_u64()).unwrap_or(0);
                if msg_type_val == 2 {
                    // PQC (type 2): parse internal PqcOlmMessage structure.
                    if let Some(body) = json_val.get("body").and_then(|b| b.as_str()) {
                        if let Ok(decoded) = B64.decode(body) {
                            if decoded.len() >= 19 {
                                let mut offset = 0;
                                offset += 1; // version
                                offset += 1; // type

                                if decoded.len() >= offset + 4 {
                                    let classic_len = u32::from_le_bytes([
                                        decoded[offset], decoded[offset+1],
                                        decoded[offset+2], decoded[offset+3]
                                    ]) as usize;
                                    offset += 4;

                                    if decoded.len() >= offset + classic_len + 5 {
                                        offset += classic_len;
                                        offset += 4; // msg_index

                                        let pqc_enabled = decoded[offset];
                                        offset += 1;

                                        if pqc_enabled == 1 && decoded.len() >= offset + 4 {
                                            let ratchet_key_len = u32::from_le_bytes([
                                                decoded[offset], decoded[offset+1],
                                                decoded[offset+2], decoded[offset+3]
                                            ]) as usize;
                                            offset += 4;

                                            self.bandwidth_initial_distribution_primitives_ratchet_key += ratchet_key_len;

                                            if decoded.len() >= offset + ratchet_key_len + 4 {
                                                offset += ratchet_key_len;

                                                let kem_ct_len = u32::from_le_bytes([
                                                    decoded[offset], decoded[offset+1],
                                                    decoded[offset+2], decoded[offset+3]
                                                ]) as usize;

                                                self.bandwidth_initial_distribution_primitives_kem_ct += kem_ct_len;

                                                let primitives_sum = megolm_key_size + ratchet_key_len + kem_ct_len;
                                                if encrypted_key.len() > primitives_sum {
                                                    self.bandwidth_initial_distribution_primitives_olm_overhead +=
                                                        encrypted_key.len() - primitives_sum;
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                } else {
                    // Classical (type 0/1): fixed 32-byte ratchet key, no KEM CT.
                    let classical_ratchet_size = 32;
                    self.bandwidth_initial_distribution_primitives_ratchet_key += classical_ratchet_size;
                    let primitives_sum = megolm_key_size + classical_ratchet_size;
                    if encrypted_key.len() > primitives_sum {
                        self.bandwidth_initial_distribution_primitives_olm_overhead +=
                            encrypted_key.len() - primitives_sum;
                    }
                }
            }
        } else if self.in_rotation_phase {
            // Key rotation phase: only messages sent inside rotate_megolm_only().
            self.bandwidth_rekeying += encrypted_key.len();
            self.time_rotation_ms += elapsed;
            
            self.bandwidth_rotation += encrypted_key.len();
            self.bandwidth_rotation_classical += classical_bytes;
            self.bandwidth_rotation_pqc += pqc_bytes;
            self.bandwidth_control_plane += encrypted_key.len();
            
            // Parse per-primitive contributions: Megolm key (308 B) + ratchet key + KEM CT.
            let megolm_key_size = 308;
            self.bandwidth_rotation_primitives_megolm_key += megolm_key_size;
            
            if let Ok(json_val) = serde_json::from_slice::<serde_json::Value>(&encrypted_key) {
                let msg_type_val = json_val.get("type").and_then(|t| t.as_u64()).unwrap_or(0);
                if msg_type_val == 2 {
                    // PQC (type 2): parse internal PqcOlmMessage structure.
                    if let Some(body) = json_val.get("body").and_then(|b| b.as_str()) {
                        if let Ok(decoded) = B64.decode(body) {
                            if decoded.len() >= 19 {
                                let mut offset = 0;
                                offset += 1; // version
                                offset += 1; // type

                                if decoded.len() >= offset + 4 {
                                    let classic_len = u32::from_le_bytes([
                                        decoded[offset], decoded[offset+1],
                                        decoded[offset+2], decoded[offset+3]
                                    ]) as usize;
                                    offset += 4;

                                    if decoded.len() >= offset + classic_len + 5 {
                                        offset += classic_len;
                                        offset += 4; // msg_index

                                        let pqc_enabled = decoded[offset];
                                        offset += 1;

                                        if pqc_enabled == 1 && decoded.len() >= offset + 4 {
                                            let ratchet_key_len = u32::from_le_bytes([
                                                decoded[offset], decoded[offset+1],
                                                decoded[offset+2], decoded[offset+3]
                                            ]) as usize;
                                            offset += 4;

                                            self.bandwidth_rotation_primitives_ratchet_key += ratchet_key_len;

                                            if decoded.len() >= offset + ratchet_key_len + 4 {
                                                offset += ratchet_key_len;

                                                let kem_ct_len = u32::from_le_bytes([
                                                    decoded[offset], decoded[offset+1],
                                                    decoded[offset+2], decoded[offset+3]
                                                ]) as usize;

                                                self.bandwidth_rotation_primitives_kem_ct += kem_ct_len;

                                                let primitives_sum = megolm_key_size + ratchet_key_len + kem_ct_len;
                                                if encrypted_key.len() > primitives_sum {
                                                    self.bandwidth_rotation_primitives_olm_overhead +=
                                                        encrypted_key.len() - primitives_sum;
                                                }

                                                vlog!(VerbosityLevel::Debug,
                                                      "         └─[PRIMITIVES] Megolm={}B, Ratchet={}B, KEM={}B, Overhead={}B",
                                                      megolm_key_size, ratchet_key_len, kem_ct_len,
                                                      encrypted_key.len() - primitives_sum);
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                } else {
                    // Classical (type 0/1): fixed 32-byte ratchet key, no KEM CT.
                    let classical_ratchet_size = 32;
                    self.bandwidth_rotation_primitives_ratchet_key += classical_ratchet_size;
                    let primitives_sum = megolm_key_size + classical_ratchet_size;
                    if encrypted_key.len() > primitives_sum {
                        self.bandwidth_rotation_primitives_olm_overhead +=
                            encrypted_key.len() - primitives_sum;
                    }
                    vlog!(VerbosityLevel::Debug,
                          "         └─[PRIMITIVES CLASSICAL] Megolm={}B, Ratchet={}B, Overhead={}B",
                          megolm_key_size, classical_ratchet_size,
                          encrypted_key.len().saturating_sub(primitives_sum));
                }
            }
            
            self.num_rotation_messages += 1;
            
            vlog!(VerbosityLevel::Normal, 
                  "      [ROTATION_MSG] {} -> {}: {} bytes (classical={}, pqc={}) [msg #{}]", 
                  sender_id, receiver_id, encrypted_key.len(), classical_bytes, pqc_bytes, 
                  self.num_rotation_messages);
        } else {
            // Normal message traffic (warm-up, re-sends).
            self.bandwidth_messages += encrypted_key.len();
            self.time_messages_ms += elapsed;
            self.bandwidth_control_plane += encrypted_key.len();
        }
        
        Ok(encrypted_key)
    }

    /// Decrypts a Megolm session key via the Olm channel (multi-sender mode).
    pub(crate) fn decrypt_megolm_key_via_olm_multi_sender(&mut self, encrypted_key: &[u8], receiver_id: &str, sender_id: &str) -> Result<Vec<u8>> {
        // Fetch sender identity before taking a mutable borrow on members.
        let sender_identity_keys = {
            let sender = self.members.get(sender_id)
                .context("Sender not found")?;
            sender.crypto.upload_identity_keys()
        };

        let receiver = self.members.get_mut(receiver_id)
            .context("Receiver not found")?;

        if let Some(existing_pair) = receiver.olm_sessions.get_mut(sender_id) {
            if let Some(inbound_session) = existing_pair.get_inbound_mut() {
                let ratchet_before = inbound_session.get_ratchet_advances();
                let asymmetric_before = inbound_session.get_asymmetric_advances();
                

                match receiver.crypto.olm_decrypt(inbound_session, encrypted_key) {
                    Ok(decrypted_bytes) => {
                        let ratchet_after = inbound_session.get_ratchet_advances();
                        let asymmetric_after = inbound_session.get_asymmetric_advances();
                        
                        if ratchet_after > ratchet_before {
                            self.num_ratchet_advances += (ratchet_after - ratchet_before) as usize;
                        }
                        if asymmetric_after > asymmetric_before {
                            self.num_asymmetric_advances += (asymmetric_after - asymmetric_before) as usize;
                        }
                        
                        return Ok(decrypted_bytes);
                    }
                    Err(_) => {
                        // Existing session failed; may be a PreKeyMessage — fall through to create a new one.
                    }
                }
            }
        }

        // Create a new inbound Olm session (first message or expired session).
        match receiver.crypto.create_inbound_session(&sender_identity_keys.curve25519, encrypted_key) {
            Ok((inbound_session, decrypted_bytes)) => {
                let ratchet_count = inbound_session.get_ratchet_advances();
                let asymmetric_count = inbound_session.get_asymmetric_advances();
                
                self.num_ratchet_advances += ratchet_count as usize;
                self.num_asymmetric_advances += asymmetric_count as usize;
                
                let pair = receiver.olm_sessions.entry(sender_id.to_string())
                    .or_insert_with(OlmSessionPair::new);
                pair.inbound = Some(inbound_session);
                
                Ok(decrypted_bytes)
            }
            Err(e) => {
                Err(anyhow::anyhow!("Decryption failed from {} to {}: {}", sender_id, receiver_id, e))
            }
        }
    }

    /// Parses an encrypted Olm message and returns the classical and PQC byte contributions.
    fn extract_message_breakdown(encrypted_message: &[u8], crypto_mode: &CryptoMode) -> (usize, usize) {
        if *crypto_mode == CryptoMode::Classical {
            return (encrypted_message.len(), 0);
        }
        
        vlog!(VerbosityLevel::Debug, "         └─[EXTRACT] analyzing message of {} bytes", encrypted_message.len());
        
        if let Ok(json_val) = serde_json::from_slice::<serde_json::Value>(encrypted_message) {
            if let Some(msg_type) = json_val.get("type").and_then(|t| t.as_u64()) {
                vlog!(VerbosityLevel::Debug, "            ├─ JSON type: {}", msg_type);
                if let Some(body) = json_val.get("body").and_then(|b| b.as_str()) {
                    if let Ok(decoded_bytes) = B64.decode(body) {
                        // Wire format (type 2): [1B version][1B classic_type][4B classic_len]
                        //   [classic_bytes][4B msg_index][1B pqc_enabled][4B ratchet_key_len]
                        //   [ratchet_key_bytes][4B kem_ct_len][kem_ct_bytes]
                        if msg_type == 2 && decoded_bytes.len() >= 19 {
                            let mut offset = 0;
                            
                            vlog!(VerbosityLevel::Debug, "            ├─ [PARSE] Total decoded: {} bytes", decoded_bytes.len());
                            
                            // 1. Version (1B)
                            let version = decoded_bytes[offset];
                            offset += 1;
                            vlog!(VerbosityLevel::Debug, "            ├─ [PARSE] Version: {}", version);
                            
                            // 2. Classic type (1B)
                            let classic_type = decoded_bytes[offset];
                            offset += 1;
                            vlog!(VerbosityLevel::Debug, "            ├─ [PARSE] Classic type: {}", classic_type);
                            
                            // 3. Classic length (4B)
                            if decoded_bytes.len() < offset + 4 {
                                return (decoded_bytes.len(), 0);
                            }
                            let classic_len = u32::from_le_bytes([
                                decoded_bytes[offset],
                                decoded_bytes[offset + 1],
                                decoded_bytes[offset + 2],
                                decoded_bytes[offset + 3],
                            ]) as usize;
                            vlog!(VerbosityLevel::Debug, "            ├─ [PARSE] Classic len: {} bytes (offset {})", classic_len, offset);
                            offset += 4;
                            
                            // 4. Classic bytes
                            if decoded_bytes.len() < offset + classic_len {
                                vlog!(VerbosityLevel::Debug, "            └─ [PARSE] insufficient bytes for classic payload");
                                return (decoded_bytes.len(), 0);
                            }
                            let classical_bytes = classic_len;
                            offset += classic_len;
                            
                            // 5. Message index (4B) + pqc_enabled (1B)
                            if decoded_bytes.len() < offset + 5 {
                                vlog!(VerbosityLevel::Debug, "            └─ [PARSE] insufficient bytes for msg_index+pqc_enabled");
                                return (classical_bytes, 0);
                            }
                            offset += 5;
                            
                            // 6. Remainder is the PQC component (ratchet key + KEM CT).
                            let pqc_bytes = decoded_bytes.len().saturating_sub(offset);
                            
                            vlog!(VerbosityLevel::Debug, "         └─[BREAKDOWN] total={} B, classical={} B, pqc={} B",
                                 decoded_bytes.len(), classical_bytes, pqc_bytes);
                            
                            return (classical_bytes, pqc_bytes);
                        }
                        
                        // Type 0/1: classical message.
                        return (decoded_bytes.len(), 0);
                    }
                }
            }
        }
        
        // Fallback: size heuristic — messages over 1500 B likely carry a PQC component.
        if encrypted_message.len() > 1500 {
            let estimated_classical = 500;
            let estimated_pqc = encrypted_message.len().saturating_sub(estimated_classical);
            vlog!(VerbosityLevel::Debug, "         └─[BREAKDOWN HEURISTIC] classical ~{} B, pqc ~{} B", 
                 estimated_classical, estimated_pqc);
            (estimated_classical, estimated_pqc)
        } else {
            (encrypted_message.len(), 0)
        }
    }
}
