//! Room member types and Olm/Megolm session handles.

use std::collections::HashMap;
use crate::core::crypto::{OlmSessionHandle, MegolmInbound, KeyAgreementStats};
use super::crypto_backend::{CryptoMode, CryptoWrapper};

/// Unique Matrix user identifier.
pub type UserId = String;

/// Bidirectional Olm session pair with another member.
pub struct OlmSessionPair {
    /// Outbound session for SENDING messages (created with create_outbound_session).
    pub outbound: Option<OlmSessionHandle>,
    /// Inbound session for RECEIVING messages (created with create_inbound_session).
    pub inbound: Option<OlmSessionHandle>,
    /// Pending KEM ciphertext generated by forced_ratchet on the INBOUND, to be consumed by the OUTBOUND.
    pub pending_kem_for_outbound: Option<Vec<u8>>,
}

impl OlmSessionPair {
    pub fn new() -> Self {
        Self {
            outbound: None,
            inbound: None,
            pending_kem_for_outbound: None,
        }
    }

    /// Returns `true` if an outbound session is established.
    pub fn has_outbound(&self) -> bool {
        self.outbound.is_some()
    }

    /// Returns a mutable reference to the outbound session, if any.
    pub fn get_outbound_mut(&mut self) -> Option<&mut OlmSessionHandle> {
        self.outbound.as_mut()
    }

    /// Returns a mutable reference to the inbound session, if any.
    pub fn get_inbound_mut(&mut self) -> Option<&mut OlmSessionHandle> {
        self.inbound.as_mut()
    }
}

/// Matrix room member.
pub struct RoomMember {
    /// Matrix user ID.
    #[allow(dead_code)]
    pub user_id: UserId,
    /// Cryptographic provider (hybrid or classical).
    pub crypto: CryptoWrapper,
    /// Olm sessions with other members (outbound + inbound per peer).
    pub olm_sessions: HashMap<UserId, OlmSessionPair>,
    /// Current inbound Megolm session (for decryption).
    pub megolm_inbound: Option<MegolmInbound>,
}

impl RoomMember {
    pub fn new_hybrid(user_id: UserId) -> Self {
        Self {
            user_id,
            crypto: CryptoWrapper::new_hybrid(),
            olm_sessions: HashMap::new(),
            megolm_inbound: None,
        }
    }

    pub fn new_classical(user_id: UserId) -> Self {
        Self {
            user_id,
            crypto: CryptoWrapper::new_classical(),
            olm_sessions: HashMap::new(),
            megolm_inbound: None,
        }
    }

    pub fn new(user_id: UserId, mode: CryptoMode) -> Self {
        match mode {
            CryptoMode::Hybrid => Self::new_hybrid(user_id),
            CryptoMode::Classical => Self::new_classical(user_id),
        }
    }
}

/// Statistics for a Megolm session.
#[derive(Debug, Default, Clone)]
pub struct MegolmSessionStats {
    pub creation_time_ms: f64,
    pub distribution_time_ms: f64,
    pub messages_encrypted: usize,
    pub total_bytes_encrypted: usize,
    #[allow(dead_code)]
    pub key_agreement_stats: KeyAgreementStats,
}
